---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-linux-deployment
  labels:
    app: alpine-linux
spec:
  replicas: 8
  selector:
    matchLabels:
      app: alpine-linux
  template:
    metadata:
        labels:
          app: alpine-linux
    spec:
      containers:
        - name: alpine-linux-container
          image: alpine:3.10
          readinessProbe:
            exec:
              command:
              - du
              - /tmp/currentdate
            initialDelaySeconds: 5
            periodSeconds: 5
          command: ["/bin/sh"]

          # create readinessProbe file to check and keep the container alive
          args: ["-c", "date > /tmp/currentdate &  while true; do sleep 1; done"]