apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
   name: allow-all-ingress-egress
spec:
   podSelector: {}
   policyTypes:
      - Ingress
      - Egress
   ingress:
      - from:
           - podSelector: {}
   egress:
      - to:
           - podSelector: {}
      - ports:
           - port: 53
             protocol: UDP
