---
- name: Deploy apache server
  hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Wait for host to become ready
    wait_for_connection:
      delay: 5
      timeout: 60
      
  tasks:
  - name: Remove apt lock file
    file:
      path: "/var/lib/dpkg/lock-frontend"
      state: absent
    
  - name: Install apache2
    apt: 
      name: apache2
      state: latest
      update_cache: yes

  - name: Run apache
    service:
      name: apache2
      state: started