- name: DumpAnsibleHostVariables
  hosts: localhost # dump what HOST controller knows, not what GUEST
  connection: local
  gather_facts: no
  tasks:
    - name: Dump all vars to file
      template:
        src: dumpall.j2 
        dest: dumped_vars.j2
