apiVersion: v2
name: mychart
description: This text shows in helm search

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.0.1

sources:
  - https://mychart.com/gitrepo

home: https://mychart.com

icon: https://mychart.com/incon.png

maintainers:
  - name: Mateusz
    email: mateusz@mateusz.com

# what other charts need to be deployed for our chart to work
# this mariadb is just for example purposes; not actually needed for hello-world to work :)
dependencies:
  - name: mariadb
    version: 7.0.0 # chart version, not app version
    repository: https://charts.bitnami.com/bitnami/ 
