# allow our pod interact with KubeAPI

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-api-client-crd-cr
rules:
- apiGroups:
  - "extensions.istio.io"
  resources:
  - wasmplugins
  verbs:
  - get
  - list
  - watch
  - patch 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-api-client-crd-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-api-client-crd-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-api-client-crd-cr
subjects:
- kind: ServiceAccount
  name: k8s-api-client-crd-sa
  namespace: default
