apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-api-client
  name: k8s-api-client
spec:
  containers:
  - image: k8s-api-client:latest
    name: k8s-api-client
    imagePullPolicy: Never # load from docker cache
  restartPolicy: Never
  serviceAccount: k8s-api-client-sa
