---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: hostvol1
  spec:
    storageClassName: "fast-and-furious"
    capacity: 
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/volumes/vol1"

---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: hostvol2
  spec:
    storageClassName: "fast-and-furious"
    capacity: 
      storage: 2Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/volumes/vol2"

---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-data
    labels:
      type: host
  spec:
    storageClassName: "fast-and-furious"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi # look for persistent volume of at least 2Gi capacity
---
  apiVersion: v1
  kind: Pod
  metadata:
    name: volumeclaim-pod
  spec:
    restartPolicy: Never
    volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: pvc-data
    containers:
      - name: volumeclaim-container
        image: alpine
        volumeMounts:
          - name: data1
            mountPath: /pod_persistent_data
        command: ["sh"]
        args: ["-c", "df -h /pod_persistent_data && sleep 5"] # sleep 5 to allow Ready state to be detected by "kubectl wait pod/hostpath-pod  --for condition=Ready"
