---
  apiVersion: v1
  kind: Pod
  metadata:
    name: hostpath-pod
  spec:
    restartPolicy: Never
    volumes:
      - name: my-shared-volume
        hostPath:
          path: /home
    containers:
      - name: hostpath-container
        image: alpine
        volumeMounts:
          - name: my-shared-volume
            mountPath: /shared
            
        command: ["sh"]
        args: ["-c", "readlink -f /shared && sleep 5"] # sleep 5 to allow Ready state to be detected by "kubectl wait pod/hostpath-pod  --for condition=Ready"
