---
  apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: hello-world-replicaset # pods will be named: hello-world-replicaset-someid
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hello-world-pod
    template:
      metadata:
        name: hello-world-pod
        labels:
          app: hello-world-pod
      spec:
        containers:
          - name: hello-world-container
            image: tutum/hello-world
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: 100m
                memory: 10Mi
            command: ["/bin/sh"]

            # make CPU busy for autoscaling to take effect. You can login and kill dd to see autoscaler removes replicas
            args: ["-c", "dd if=/dev/zero of=/dev/null &  while true; do sleep 1; done"]