---
service:
  public:
    type: NodePort # so you can connect to cluster from outside 

statefulset:
  replicas: 3 # 3 cockroachdb cluster nodes

storage:
  persistentVolume:
    enabled: true
    size: 2Gi
    # storageClass: karaluch # first need to create PersistentVolume with this storageClass
