---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: my-config-map 
  labels:
    app: alpine-linux-pod
data:
  CONFIGMAP_PROJECT_NAME: "Shamrock Project"
  CONFIGMAP_PROJECT_VER: "v0.1"
  CONFIGMAP_PROJECT_WEB: "www.shamrock.pl"
      
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-linux-pod
spec:
  volumes:
    - name: config-volume 
      configMap:
        name: my-config-map # this volume will hold configmap as files, where filename = key, filecontents = value
    
  containers:
    - name: alpine-linux-container
      image: alpine:3.10
      command: ["/bin/sh"]
      args: ["-c", "env | grep CONFIG & find /config/CONFIG* & while true; do sleep 1; done"]
      

      # mount configmap as volume
      volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        
      # inject configmap as env variables
      envFrom:
        - configMapRef:
            name: my-config-map

