- name: Deploy a counting script on host
  hosts: all
  gather_facts: no
  pre_tasks:
    # python is precondition for modules other than "raw" to work
    - name: Update package index
      raw: apk update # alpine linux package manager
    - name: Install python3
      raw: apk add python3 # alpine linux package manager

  # roles are templated tasks that take input variables
  roles:
    - name: run_server # == role directory name

      