---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-linux-pod
spec:
  # volume to mount secrets as files
  volumes:
    - name: secret-volume 
      secret:
        secretName: mysecret # this volume will hold secrets as files, where filename = key, filecontents = value

  containers:
    - name: alpine-linux-container
      image: alpine:3.10
      command: ["/bin/sh"]
      args: ["-c", "env | grep SECRET & find /secret/SECRET* & sleep 5"] # sleep 5 for kubectl wait to detect POD in ready state

      # mount secret as volume
      volumeMounts:
        - name: secret-volume
          mountPath: /secret # mysecret.data will be here as files
          readOnly: true

      # inject secret as env variables
      envFrom:
        - secretRef:
            name: mysecret
      

