---
  # checker-deployment. 2 containers: digitchecker, pngconverter. 1 volume: shared-data
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: checker-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: checker
  
    template:
      metadata:
          labels:
            app: checker
      spec:
        volumes:
          - name: shared-data
            emptyDir: {}
        containers:
          - name: digitchecker
            image: mateuszmidor/digitcheck-digitchecker
            imagePullPolicy: Never # use local image
            ports:
              - containerPort: 80
            volumeMounts:
              - name: shared-data
                mountPath: /tmp
  
          - name: pngconverter
            image: mateuszmidor/digitcheck-pngconverter
            imagePullPolicy: Never # use local image
            ports:
              - containerPort: 81
            volumeMounts:
              - name: shared-data
                mountPath: /tmp