apiVersion: v1
kind: Pod
metadata:
  labels:
    run: http-server
  name: http-server
spec:
  containers:
  - image: http-server-img
    name: http-server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
