---
  # checker-deployment. 2 containers: digitchecker, pngconverter. 1 volume: shared-data
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: checker-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        digitrecon: checker
  
    template:
      metadata:
          labels:
            digitrecon: checker
      spec:
        volumes:
          - name: shared-data
            emptyDir: {}
        containers:
          - name: digitchecker-container
            image: mateuszmidor/digitrecon-digitchecker
            imagePullPolicy: Never # use local image
            ports:
              - containerPort: 80
            volumeMounts:
              - name: shared-data
                mountPath: /tmp
            readinessProbe: # it takes time to learn digit recognition, so let kubernetes check for readiness
              httpGet:
                path: /healthcheck
                port: 80
              initialDelaySeconds: 60
              periodSeconds: 5
  
          - name: pngconverter-container
            image: mateuszmidor/digitrecon-pngconverter
            imagePullPolicy: Never # use local image
            ports:
              - containerPort: 81
            volumeMounts:
              - name: shared-data
                mountPath: /tmp