@startuml "c1"

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
!include C4PUML/C4-PlantUML/C4_Context.puml

title System-Level diagram for DigitCheck
LAYOUT_TOP_DOWN

#Person(user, "digit hand writer", "")

Enterprise_Boundary(c1, "DigitCheck LTD.") {
    System(digit_checker, "DigitCheck", "hand-written digit recognition system")
}

Rel(user, digit_checker, "draw a digit, read the result")

@enduml