---
- name: Add users
  user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}" 
    create_home: true
    expires: -1
    comment: "Ansible-created account"
  loop: "{{ users }}"

- name: Install SSH Keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    manage_dir: true
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop: "{{ users }}"

- name: Setup sudo accesss
  copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ users }}"