# create secret "mysecret" from files
# this will result in:
# mounted volume files:
#   /secret/SECRET_USER
#   /secret/SECRET_PASS
#   /secret/SECRET_COLORS
# env variables:
#   SECRET_COLORS=
#   SECRET_R=red
#   SECRET_B=blue
#   SECRET_G=green
#   SECRET_PASS=my_secret_user
#   SECRET_USER=my_secret_pass

secretGenerator:
  - name: mysecret
    files:
      - SECRET_USER
      - SECRET_PASS
      - SECRET_COLORS
generatorOptions:
  disableNameSuffixHash: true # dont randomize name