---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-linux-pod
spec:
  volumes:
    - name: secret-volume 
      secret:
        secretName: mysecret # this volume will hold secrets as files, where filename = key, filecontents = value

  containers:
    - name: alpine-linux-container
      image: alpine:3.10
      command: ["/bin/sh"]
      args: ["-c", "env | grep SECRET & find /secret/SECRET* & while true; do sleep 1; done"]

      # mount secret as volume
      volumeMounts:
        - name: secret-volume
          mountPath: /secret # mysecret.data will be here as files
          readOnly: true

      # inject secret as env variables
      env:
        - name: SECRET_USER # will become env variable SECRET_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SECRET_USER
        - name: SECRET_PASS # will become env variable SECRET_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SECRET_PASS