version: "3.9"
services:
  envoy:
    image: envoyproxy/envoy:v1.22-latest
    hostname: envoy
    networks:
      - talker-net
    ports:
      - "9901:9901" # envoy admin interface for fetching stats with: curl localhost:9901/stats?format=json
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - frozen-camp
      - frosty-colony
      - danzig 
      - cracovia
      - luang_prabang
      - chiang_rai
      - cleveland
      - tucson

  ##### cluster: antarctica (responses with huge latency, tiny messages, little errors)
  frozen-camp:
    build: .
    hostname: frozen-camp
    environment:
      TALKERS: "http://envoy:2000" # talk to european cities
      MAX_RESPONSE_PAYLOAD_BYTES: 10
      MIN_RESPONSE_LATENCY_MS: 5000
      MAX_RESPONSE_LATENCY_MS: 10000      
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3         
    networks:
      - talker-net
  frosty-colony:
    build: .
    hostname: frosty-colony
    environment:
      TALKERS: "http://envoy:2000" # talk to european cities
      MAX_RESPONSE_PAYLOAD_BYTES: 10
      MIN_RESPONSE_LATENCY_MS: 5000
      MAX_RESPONSE_LATENCY_MS: 10000      
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3       
    networks:
      - talker-net

  ##### cluster: europe (responses with low latency, small messages, little errors)
  danzig:
    build: .
    hostname: danzig
    environment:
      TALKERS: "http://envoy:1000" # talk to antarctica cities
      MAX_RESPONSE_PAYLOAD_BYTES: 5000
      MIN_RESPONSE_LATENCY_MS: 50
      MAX_RESPONSE_LATENCY_MS: 100      
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3         
    networks:
      - talker-net
  cracovia:
    build: .
    hostname: cracovia
    environment:
      TALKERS: "http://envoy:1000" # talk to antarctica cities
      MAX_RESPONSE_PAYLOAD_BYTES: 5000
      MIN_RESPONSE_LATENCY_MS: 50
      MAX_RESPONSE_LATENCY_MS: 100    
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3       
    networks:
      - talker-net

  ##### cluster: asia (responses with moderate latency, huge messages, many errors)
  luang_prabang:
    build: .
    hostname: luang_prabang
    environment:
      TALKERS: "http://envoy:4000" # talk to american cities
      MAX_RESPONSE_PAYLOAD_BYTES: 1000000
      MIN_RESPONSE_LATENCY_MS: 2000
      MAX_RESPONSE_LATENCY_MS: 5000
      STATUS_200_WEIGHT: 70
      STATUS_300_WEIGHT: 10
      STATUS_400_WEIGHT: 10
      STATUS_500_WEIGHT: 10     
    networks:
      - talker-net
  chiang_rai:
    build: .
    hostname: chiang_rai
    environment:
      TALKERS: "http://envoy:4000" # talk to american cities
      MAX_RESPONSE_PAYLOAD_BYTES: 1000000
      MIN_RESPONSE_LATENCY_MS: 2000
      MAX_RESPONSE_LATENCY_MS: 5000
      STATUS_200_WEIGHT: 70
      STATUS_300_WEIGHT: 10
      STATUS_400_WEIGHT: 10
      STATUS_500_WEIGHT: 10   
    networks:
      - talker-net

  ##### cluster: america (responses with low latency, small messages, little errors)
  cleveland:
    build: .
    hostname: cleveland
    environment:
      TALKERS: "http://envoy:3000" # talk to asian cities
      MAX_RESPONSE_PAYLOAD_BYTES: 5000
      MIN_RESPONSE_LATENCY_MS: 50
      MAX_RESPONSE_LATENCY_MS: 100      
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3        
    networks:
      - talker-net
  tucson:
    build: .
    hostname: tucson
    environment:
      TALKERS: "http://envoy:3000" # talk to asian cities
      MAX_RESPONSE_PAYLOAD_BYTES: 5000
      MIN_RESPONSE_LATENCY_MS: 50
      MAX_RESPONSE_LATENCY_MS: 100      
      STATUS_200_WEIGHT: 90
      STATUS_300_WEIGHT: 4
      STATUS_400_WEIGHT: 3
      STATUS_500_WEIGHT: 3       
    networks:
      - talker-net
networks:
  talker-net:
    name: talker-net
    driver: bridge