---
  apiVersion: v1
  kind: Pod
  metadata:
    name: alpine-linux-pod
  spec:
    volumes:
      - name: config-volume 
        configMap:
          name: my-config-map # created by run_all.sh from pod.properties

    containers:
      - name: alpine-linux-container
        image: alpine:3.10
        # envFrom:
        #   - configMapRef:
        #       name: my-config-map # created in run_all.sh from pod.properties
        volumeMounts:
          - name: config-volume
            mountPath: /config/ # pod.properties will be here
        command: ["/bin/sh"]
        args: ["-c", "cat /config/pod.properties & while true; do sleep 1; done"]
