apiVersion: v1
kind: Pod
metadata:
  name: server
  annotations:
    # here we define custom network that we want attached in our POD
    k8s.v1.cni.cncf.io/networks:
      '[
        {
          "name": "macvlan-conf",
          "interface": "my-intf",
          "ips": [ "192.168.1.88/24" ],
          "gateway": [ "192.168.1.254" ]
        }
      ]'

spec:
  containers:
    - name: server
      command:
        [
          "/bin/ash",
          "-c",
          # serve "/" directory over HTTP on static IP
          "python -m http.server 8888 --bind 192.168.1.88 --directory /",
        ]
      image: python:alpine3.16

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  annotations:
    # here we define custom network that we want attached in our POD
    k8s.v1.cni.cncf.io/networks:
      '[
        {
          "name": "macvlan-conf",
          "interface": "my-intf",
          "ips": [ "192.168.1.44/24" ],
          "gateway": [ "192.168.1.254" ]
        }
      ]'

spec:
  containers:
    - name: client
      command:
        [
          "/bin/ash",
          "-c",
          # send GET to our server listening in custom network
          "while true; do curl --silent --interface my-intf 192.168.1.88:8888; sleep 1; done",
        ]
      image: alpine/curl:3.14
