apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tt-reports.fullname" . }}
stringData:
  INPUT_GD_EMAIL: {{ .Values.config.InputData.GoogleDrive.Email }}
  INPUT_GD_PRIVATE_KEY: | 
    {{- .Values.config.InputData.GoogleDrive.PrivateKey | nindent 4 }}
  INPUT_GD_JOBS_FILENAME_PATTERN: {{ .Values.config.InputData.GoogleDrive.JobsFilenamePattern }}
  INPUT_GD_CANDIDATES_FILENAME_PATTERN: {{ .Values.config.InputData.GoogleDrive.CandidatesFilenamePattern }}
 
  OUTPUT_GD_EMAIL: {{ .Values.config.OutputData.GoogleDrive.Email }}
  OUTPUT_GD_PRIVATE_KEY: |
    {{- .Values.config.OutputData.GoogleDrive.PrivateKey | nindent 4 }}
  OUTPUT_GD_FOLDER_ID: {{ .Values.config.OutputData.GoogleDrive.FolderID }}
  OUTPUT_GD_FILENAME: {{ .Values.config.OutputData.GoogleDrive.FileName }}
 
  PERSISTENCE_MONGO_ENDPOINT: {{ .Values.config.Persistence.Mongo.Endpoint }}
  PERSISTENCE_MONGO_COLLECTION: {{ .Values.config.Persistence.Mongo.Collection }}
  PERSISTENCE_MONGO_USER: {{ .Values.config.Persistence.Mongo.UserName }}
  PERSISTENCE_MONGO_PASS: {{ .Values.config.Persistence.Mongo.UserPass }}
 
  REPORT_UPDATE_FREQUENCY: {{ .Values.config.ReportUpdateFrequency }}
  DATA_POINT_COUNT_LIMIT: {{ .Values.config.DataPointCountLimit | quote}}
