- name: hostvars demo
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Print description of first host in groups 'cheaphosts'
      debug:
        var: hostvars[groups['cheaphosts'][0]].description

    - name: Print description of host 'localhost'
      debug:
        var: hostvars['localhost'].description