- name: hostvars demo
  hosts: localhost
  gather_facts: no
  vars:
    description: "Playbook local description" # this overrides the description assigned to localhost
  tasks:
    - name: Print host-related var using hostvars
      debug:
        var: hostvars['localhost'].description

    - name: Print host-related var the direct way
      debug:
        var: description