---
  apiVersion: v1
  kind: Service
  metadata:
    name: hello-world-service
  spec:
    type: NodePort
    selector:
      # Route the traffic to PODs with following label
      app: hello-world-pod
    ports:
      - protocol: "TCP"
        # Port accessible inside cluster. It forwards to targetPort 80 inside pod
        port: 8080
        # Port To forward to inside pod
        targetPort: 80
   
---
  apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: hello-world-replicaset # pods will be named: hello-world-replicaset-someid
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: hello-world-pod
    template:
      metadata:
        name: hello-world-pod
        labels:
          app: hello-world-pod
      spec:
        containers:
          - name: hello-world-container
            image: tutum/hello-world
            ports:
              - containerPort: 80