---
  apiVersion: v1
  kind: Pod
  metadata:
    name: producer-consumer
  spec:
    volumes:
      - name: shared-data
        emptyDir: {}
    containers:
      - name: producer
        image: alpine
        volumeMounts:
          - name: shared-data
            mountPath: /shared-data
        command: ["sh"]

        # write time in format: 19:45:59 to /shared-data/myfile
        args: ["-c", "while true; do echo `date +%T` >> /shared-data/myfile; sleep 1; done"]

      - name: consumer
        image: alpine
        volumeMounts:
          - name: shared-data
            mountPath: /shared-data
        command: ["sh"]

        # read time from /shared-data/myfile
        args: ["-c", "tail -f /shared-data/myfile"]