---
fullnameOverride: mychartmuseum

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - charts.127.0.0.1.nip.io:
        - /
        - /index.yaml
env:
  open:
    STORAGE: local
    DEBUG: false
    LOG_JSON: true
    DISABLE_METRICS: true
    DISABLE_API: false
    ALLOW_OVERWRITE: true