---
fullnameOverride: mychartmuseum

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - charts.127.0.0.1.nip.io: # '127.0.0.1' to be overriden with minikube ip in helm install --set
        - /
        - /index.yaml # this is actual list of available charts; will contain "mychart"
env:
  open:
    STORAGE: local
    DEBUG: false
    LOG_JSON: true
    DISABLE_METRICS: true
    DISABLE_API: false
    ALLOW_OVERWRITE: true