apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090 # prometheus runs at this port
    editable: true # configuration of this datasource can be edited in dashboard
