- name: Prepare instances for ansible actions
  hosts: all
  gather_facts: no
  pre_tasks:
    # python is precondition for modules other than "raw" to work
    - name: Update package index
      raw: apk update # alpine linux package manager
    - name: Install python3
      raw: apk add python3 # alpine linux package manager

    - name: Install pip
      apk: 
        name: py3-pip
        state: latest
    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
      